version: '3.8'
services:

  mongo-db:
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    environment:
      MONGODB_INITIAL_PRIMARY_ROOT_USER: ${MONGODB_ADMIN_USER}
      MONGODB_ROOT_USER: ${MONGODB_ADMIN_USER}
      MONGODB_ROOT_PASSWORD: ${MONGODB_ADMIN_PASS}
      MONGODB_REPLICA_SET_MODE: primary
      ALLOW_EMPTY_PASSWORD: 'yes'
      MONGODB_REPLICA_SET_KEY: ${REPLICA_SET_KEY}
    volumes:
      - ./mongodata:/data/db

  node-app:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_DB_USERNAME: ${MONGODB_ADMIN_USER}
      MONGO_DB_PASS: ${MONGODB_ADMIN_PASS}
      MONGO_DB_URL: mongodb://${MONGODB_ADMIN_USER}:${MONGODB_ADMIN_PASS}@mongo-db:27017/
      MAIL_SERVICE: ${MAIL_SERVICE}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      AUTH_TOKEN_KEY: ${AUTH_TOKEN_KEY}
    depends_on:
      - mongo-db
    volumes:
      - ./src/uploads/images:/app/src/uploads/images
    stdin_open: true
    tty: true

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMIN_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_URL: mongodb://mongo-db:27017/
    depends_on:
      - mongo-db
  
volumes:
  mongoVol: